### ISSUE TITLE
Help on compile

### ISSUE THREAD

**Issue by JeanGrim** [Jack000/Deepnest#118]
Hi, I am trying to compile this project, but if I try with node 6.9.5 and npm 3.10.10 I got the following error with npm 

```
  npm.load(async er => {
           ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jeanc\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:2:1)
    at Module._compile (module.js:570:32)

```

if I try to compile with Node 15.8.0 and npm 7.5.1 I got the following error

```
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.8.0 | win32 | x64
gyp info find Python using Python version 2.7.3 found at "C:\Python27\python.exe"
gyp info find VS using VS2019 (16.8.30907.101) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\jeanc\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jeanc\\Desktop\\Deepnest-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jeanc\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jeanc\\AppData\\Local\\node-gyp\\Cache\\15.8.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jeanc\\AppData\\Local\\node-gyp\\Cache\\15.8.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jeanc\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jeanc\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.8.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\jeanc\\Desktop\\Deepnest-master',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\jeanc\\Desktop\\Deepnest-master\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- C:\Users\jeanc\Desktop\Deepnest-master\[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:131:12)
    at Object.runInThisContext (node:vm:308:38)
    at node:internal/process/execution:77:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:76:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\jeanc\\Desktop\\Deepnest-master\\[eval]' ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\jeanc\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jeanc\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\jeanc\Desktop\Deepnest-master
gyp ERR! node -v v15.8.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```

Can someone help me on compile this? I would like to compile on Windows 10 Pro with VS2019

Regards

**Comment by Giulio1980** [comment]
I compiled on VSCode 2021on Win 8.1, installed electron, fix a minor thing on the main.js.
Now it compiles but it's non responsive. I mean I can only close it
Any luck?
